# Generated by Django 4.2.4 on 2023-09-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('element', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('power', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
